@echo off
start cmd /c "python main.py --logic Random --email=test@email.com --name=stima --password=123456 --team etimo"
start cmd /c "python main.py --logic NewBot --email=welae@email.com --name=nearest1 --password=123456 --team etimo"
start cmd /c "python main.py --logic TestBot --email=tessst2@email.com --name=ratio1 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic NewBot --email=aaxa@email.com --name=nearest2 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TestBot --email=tesst2@email.com --name=ratio2 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic NewBot --email=aaxaa@email.com --name=nearest3 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TestBot --email=testd2@email.com --name=ratio3 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic NewBot --email=aaxaw@email.com --name=nearest4 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TestBot --email=tests2@email.com --name=ratio4 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test3@email.com --name=stima3 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test4@email.com --name=stima4 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test5@email.com --name=stima5 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test6@email.com --name=stima6 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test7@email.com --name=stima7 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test8@email.com --name=stima8 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test9@email.com --name=stima9 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test10@email.com --name=stima10 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test11@email.com --name=stima11 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test12@email.com --name=stima12 --password=123456 --team etimo"
