@echo off
@REM start cmd /c "python main.py --logic Random --email=test@email.com --name=stima --password=123456 --team etimo"
start cmd /c "python main.py --logic Angie1 --email=welee@email.com --name=Angie1 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Angie2 --email=tess1t2@email.com --name=Angie2 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Neo1 --email=akaxa@email.com --name=Neo1 --password=123456 --team etimo"
start cmd /c "python main.py --logic Neo2 --email=dtesst2@email.com --name=Neo2 --password=123456 --team etimo"
start cmd /c "python main.py --logic Azul --email=aaxada@email.com --name=Azul --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TestBot --email=testd2@email.com --name=ratio3 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic NewBot --email=aaxaw@email.com --name=nearest4 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic TestBot --email=tests2@email.com --name=ratio4 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test3@email.com --name=stima3 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test4@email.com --name=stima4 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test5@email.com --name=stima5 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test6@email.com --name=stima6 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test7@email.com --name=stima7 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test8@email.com --name=stima8 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test9@email.com --name=stima9 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test10@email.com --name=stima10 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test11@email.com --name=stima11 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test12@email.com --name=stima12 --password=123456 --team etimo"
